### ISSUE TITLE
Workspace syncing among the instances

### ISSUE THREAD

**Issue by remohammadi** [cafebazaar/blacksmith#26]
Currently, it's the task of the user to sync the workspace among the instances, so if the master fails for some reason, the next master be as uptodate as the first one.

In practice, the lack of syncing mechanism makes the "files" feature useless.

**Comment by farnasirim** [comment]
I suggest notifying other machines of changes to files directories by setting etcd flags which are being watched by machines. Pull requests can be placed using etcd "create in order" so that multiple pull requests that happen between two etcd heartbeats won't be problematic. What remains is where/how/whether (and how far back) to keep the files or files directory differences (e.g. in case a machine comes up after a long downtime with an outdated files directory or a new machine).

**Comment by farnasirim** [comment]
Any progress? @remohammadi @mehdy

**Comment by remohammadi** [comment]
@colonelmo
@mehdy and @alaee have a cool idea for this: to add the file-info of an uploaded file to the etcd dir, so the other instances be notified (by watching or regular checks?) and start to download it when they have not the file / have an outdated one.

**Comment by farnasirim** [comment]
@remohammadi Yea I caught up with @mehdy and the idea sounds pretty neat imo. Thanks!
